config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  get 'apps/calificacion'
  devise_for :admins, controllers: {sessions: 'admini'}
  resources :apps
  devise_for :users, controllers: {registrations: 'registro'}
  root :to => "inicio#index"
  post 'ratings/new'
  post 'apps/filtros'
  get 'dashboard', :to => "inicio#dashboard"
  resources :valoracions
  get 'nueva-valoracion', :to => "valoracions#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :app
  belongs_to :user
  belongs_to :valoracion
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:create]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
    @valoraciones=Valoracion.all
  @app=App.find(params[:id])
  @p=params[:id]
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    val=Valoracion.all
    c=0
    u=Unique.find_by_unique(params[:rating][:unique])
    if u.nil?
      unique=Unique.create(:unique => params[:rating][:unique])
        f=params[:rating][:valoracion]
            val.each do |app|
              sql=  Rating.create(:user_id => params[:rating][:user_id],
                            :app_id=> params[:rating][:app_id],
                            :valoracion_id => app.id,
                            :valor => f[app.nombre]
                            )
                            if sql.save
                              c=c+1
                            end

            end
            if c==val.size
              redirect_to apps_url
                 flash[:notice] ="Muchas gracias tu calificacion nos sirven "
            end
      else
        redirect_to :back
        flash[:notice] ="No puedes calificar ds veces la misma aplicacion"
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:app_id, :user_id,:valoracion_id,:valor)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for(rating) do |f| %>
  <% if rating.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
		<ol class="breadcrumb">
			<li><a href="<%= root_path%>">Inicio</a></li>
			<li><a href="apps_path">Aplicaciones</a></li>
			<li class="active"><?php echo ucfirst($nombre); ?></li>
		</ol>

		<div class="col-md-3">
			<div class="panel panel-default">
				<div class="panel-heading"><h4 class="text-muted" style="font-weight: bold;">Características</h4></div>
				<div class="panel-body">
          <h5 class="text-muted"><b>Plataforma: </b><%= @app.plataforma%></h5>
					<h5 class="text-muted"><b>Idioma: </b><%= @app.idioma%></h5>

					<h5 class="text-muted"><b>Sitio Web Oficial: </b><a href="http://<%= @app.sitio_web%>" target="_blank"><%=@app.sitio_web%></a></h5>
				</div>
			</div><hr>
		</div>

		<div class="col-md-9" style="border-left: 1px dotted #e0e0e0; border-width: thin; margin-bottom: 10px;">
			<div >
				<table class="table table-hover">
				    <thead>
				    	<tr colspan="3"><h3 style="font-weight: bold; text-align: center;">VALORACIÓN <br><small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis nam deserunt et quidem, magni dignissimos provident ipsa? Veniam fuga, itaque aut blanditiis non, nobis beatae explicabo exercitationem iste, ullam sint.</small></h3></tr>
						<tr>
							<th width="10%" style="text-align: center;">ID</th>
					        <th width="50" style="text-align: center;">CRITERIOS</th>
					        <th width="40%" style="text-align: center;">VALORACIÓN</th>
					     </tr>
				    </thead>
				    <tbody><%c=1%>
              <%o=0%>
              <% @valoraciones.each do |v|%>
  						<tr>

                <td style="text-align: center;"><%=c%></td>
                <td><%=v.nombre.capitalize%></td>
                <td style="text-align: center;">

                <input type="text" name="rating[valoracion][<%=v.nombre%>]" class="rating" step="0.1" required="true">
                 </td>
                <%c=c+1
                o=o+1
                %>
  						</tr>
            <% end %>
				    </tbody>
				  </table>
				  <hr><br>
          <% if user_signed_in? %>
             <%= f.hidden_field :user_id, value: current_user.id %>
             <%= f.hidden_field :app_id, value:@p %>
             <input type="hidden" name="rating[unique]" value="<%=@p%><%=current_user.id%>">

          <% end %>
            <%= f.submit "Calificar", class:"btn btn-lg btn-primary", style:"width: 40%; margin: 0 auto; display: block;" %>
            <%= @pr%>
			  </div>
		</div>
	</div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ratings</h1>

<table>
  <thead>
    <tr>
      <th>App</th>
      <th>User</th>
      <th>Claridad</th>
      <th>Motivacion</th>
      <th>Contenido</th>
      <th>Interaccion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.app %></td>
        <td><%= rating.user %></td>
        <td><%= rating.claridad %></td>
        <td><%= rating.motivacion %></td>
        <td><%= rating.contenido %></td>
        <td><%= rating.interaccion %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form', rating: @rating %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>App:</strong>
  <%= @rating.app %>
</p>

<p>
  <strong>User:</strong>
  <%= @rating.user %>
</p>

<p>
  <strong>Claridad:</strong>
  <%= @rating.claridad %>
</p>

<p>
  <strong>Motivacion:</strong>
  <%= @rating.motivacion %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @rating.contenido %>
</p>

<p>
  <strong>Interaccino:</strong>
  <%= @rating.interaccion %>
</p>