config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  get 'apps/calificacion'
  devise_for :admins, controllers: {sessions: 'admini'}
  resources :apps
  devise_for :users, controllers: {registrations: 'registro'}
  root :to => "inicio#index"
  post 'ratings/new'
  post 'apps/filtros'
  get 'dashboard', :to => "inicio#dashboard"
  resources :valoracions
  get 'nueva-valoracion', :to => "valoracions#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/apps/_form.html.erb
<%= form_for(app) do |f| %>
  <% if app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
  	<ol class="breadcrumb">
  		<li><a href="/dashboard">Administrar aplicaciones</a></li>
  		<li class="active">Nueva aplicación</li>
  	</ol>
  	<div class="col-md-2"></div>
  	<div class="col-md-8">
  			<form method="POST" class="form-horizontal">
  				<div class="form-group">
  			        <div class="col-xs-9">
                    <%=  f.text_field :titulo,placeholder:"Titulo", required:true, autofocus:"true",class:"form-control"%>
  			        </div>
  			    </div>
  				<div class="form-group">

  			        <div class="col-xs-9">
                  <%= f.text_area :cuerpo, class:"form-control",rows:"7",style:"resize: none;",placeholder:"Escribe una breve descripción de la aplicación..." %>
  			        </div>
  			  </div>
               <div class="">

                 <div class="col-xs-9">
                   <%= f.select :plataforma,[["Selecciona el area",""],["Electronica","Electronica"],["Electricidad","Electricidad"],
                   ["Algebra","Algebra"],["Trigonometria","Trigonometria"],
                   ["Calculo","Calculo"],
                   ["Estadistica","Estadistica"],["Matematicas","Matematicas"]] %>
                 </div>
               </div>
  			    <div class="form-group">

  			        <div class="col-xs-9">
  			            <%= f.select :plataforma,[["Selecciona la plataforma",""],["web","web"],["escritorio","escritorio"],["movil","movil"]],class:"form-control" %>
  			        </div>
  			    </div>
  			    <div class="form-group">

  			        <div class="col-xs-9">
  			            <%= f.select :idioma,[["Selecciona EL idioma",""],["Ingles","Ingles"],["Español","Español"]]
                    %>
  			        </div>
  			    </div>
  			    <div class="form-group">

  			        <div class="col-xs-9">
  			          <%= f.text_field :sitio_web %>
  			        </div>
  			    </div>
            <div class="">
              <div class="field">
                    <%= f.file_field :imagen %>
             </div>
            </div>
  			    <hr>
  			    <div class="form-group">

  			        <div class="col-xs-9">
  			            <%= f.select :rol, [["Rol que cumple",""],["estudiante","estudiante"],["profesor","profesor"]] %>
  			        </div>
  			  </div>
  				<hr>
  				<button type="submit" class="btn btn-lg btn-success" name="btnCrear_app" style="width: 50%; margin: 0 auto; display: block;">Guardar <i class="fa fa-angle-double-right"></i></button>

  	</div>
  	<div class="col-md-2"></div>
  </div><br>

  	<script type="text/javascript">
          $(document).ready(function () {
              $('#example1').datepicker({
                  format: "dd/mm/yyyy"
              });
          });
      </script>
<% end %>

app/views/apps/_tbody.html.erb
  <% @apps.each do |app| %>
  <tr onclick="document.location='apps/<%= app.id %>'" style="cursor:pointer">
      <td><%= app.titulo %></td>
      <td><%= truncate(app.cuerpo, :length => 20) %></td>
      <td>
        <%= form_tag({:controller => "ratings", :action => "new"}, :method => "get") do %>
        <%= hidden_field_tag :id, app.id%>
        <%= submit_tag  app.titulo, id: app.titulo,name: "",class:"roles"%>
        <label for="<%= app.titulo%>"><a type="button" title="Valorar aplicación" class="btn btn-primary" data-toggle="tooltip" data-placement="top" ><i class="fa fa-check"></i></a></label>
       <% end %>
      </td>

  </tr>
  <% end %>

app/views/apps/edit.html.erb
<h1>Editar aplicaion</h1>

<%= render 'form', app: @app %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/filtros.js.erb
<% if @apps
  @apps.each do |app| %>

$("tbody").html('<%= j render "tbody" %>')
 <% end %>
<%end%>

app/views/apps/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
 <ol class="breadcrumb">
   <li><a href="<%= root_path%>">Inicio</a></li>
 </ol>

 <div class="col-md-3" style="border-right: 1px dotted #e0e0e0; border-width: thin; margin-bottom: 10px;">
   <div class="panel panel-default">
     <div class="panel-heading"><h4 class="text-muted" style="font-weight: bold;">Filtro</h4></div>
     <div class="panel-body">
       <hr>
       <%= form_tag({:controller => "apps", :action => "filtros"}, :method => "post",:id => "filtros", :remote => true) do %>
       <div class="form-group">
         <label for="txtCategoria" class="control-label">Rol</label>
         <select name="rol" id="" class="form-control">
           <option value="">--- Seleccione ---</option>
            <option value="estudiante">Estudiante</option>
             <option value="profesor">Profesor</option>
         </select>
       </div><hr>
       <div class="form-group">
         <label for="txtPlataforma" class="control-label">Plataforma</label>
         <select name="plataforma" id="" class="form-control">
           <option value="">--- Seleccione ---</option>
           <option value="web">Web</option>
           <option value="escritorio">Escritorio</option>
           <option value="movil">Móvil</option>
         </select>
       </div><hr>
       <div class="form-group">
         <label for="txtCompetencias" class="control-label">Area</label>
         <select name="area" id="" class="form-control">
           <option value="">--- Seleccione ---</option>
         </select>
       </div>
       <div class="form-group">
         <center><input type="submit"  value="Filtrar" class="btn btn-info"></center>
       </div>
       <% end %>
     </div>
   </div>
 </div>
 <div class="col-md-9">
   <div class="panel panel-default">
     <div class="panel-body">
       <h1 class="text-muted">Aplicaciones</h1><hr>
     </div>
     <table class="table table-hover" style="text-align: center;">
       <thead style="font-weight:bold;">
         <tr style="background:#f5f5f5; font-size:15px;">
           <td>Nombre</td>
           <td>Descripcion</td>
           <td></td>
         </tr>
       </thead>
       <tbody>
       <%= render "tbody"   %>
       </tbody>
     </table>
   </div>
 </div>
</div>

app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form', app: @app %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
		<ol class="breadcrumb">
			<li><a href="<%= root_path%>">Inicio</a></li>
			<li><a href="<%= apps_path%>">Aplicaciones</a></li>
			<li class="active"><?php echo ucfirst($nombre); ?></li>
		</ol>
    <%= form_tag({:controller => "ratings", :action => "new"}, :method => "get") do %>
		<%= hidden_field_tag :id, @app.id%>
		<%= submit_tag  @app.titulo, id: @app.titulo,name: "",class:"roles"%>
    <label for="<%= @app.titulo%>">	<a  class="btn btn-lg btn-danger" style="width: 220%;" data-toggle="tooltip" data-placement="top" title="Valorar aplicación">Calificar <i class="fa fa-check"></i></a></label>
   <% end %>
		<div class="col-md-3">
			<hr>
			<div class="panel panel-default">
				<div class="panel-heading"><h4 class="text-muted" style="font-weight: bold;">Características</h4></div>
				<div class="panel-body">
          	<h5 class="text-muted"><b>Nombre: </b><%= @app.titulo%></h5>
					<h5 class="text-muted"><b>Plataforma: </b><%= @app.plataforma%></h5>
					<h5 class="text-muted"><b>Idioma: </b><%= @app.idioma%></h5>
					<h5 class="text-muted"><b>Sitio Web Oficial: </b><a href="http://<%= @app.sitio_web%>" target="_blank"><%=@app.sitio_web%></a></h5>
				</div>
			</div><hr>
			<div class="panel panel-default">
				<div class="panel-heading"><h4 class="text-muted" style="font-weight: bold;">Criterios evaluativos</h4></div>
				<div class="panel-body">
					<%@valoraciones.each do |valoraciones|%>
					   <h5 class="text-muted" style="color: #303f9f;"><b><%= valoraciones.nombre.capitalize%> </b><input id="input-21e" value="<%=Rating.where(:app_id => params[:id]).where(:valoracion_id => valoraciones.id).average(:valor )%>" data-size="xs"  data-show-clear="false" type="number" class="rating " min=0 max=5 step=0.5 data-size="xs" disabled></h5>
					<% end %>
				</div>
			</div><hr>
		</div>

		<div class="col-md-9" style="border-left: 1px dotted #e0e0e0; border-width: thin; margin-bottom: 10px;">
			<div class="panel panel-default">
				<div class="panel-body">
					<h1 class="text-muted"><%=@app.titulo%></h1><hr>
					<div class="well">
						<img src="<%=@app.imagen.url%>" width="100%" height="300" class="img img-rounded">

					</div><hr>
					<h4 class="text-muted">Descripcion</h4>
					<p><%= @app.cuerpo%></p>
				</div>
			</div>
		</div>
	</div>