config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  get 'apps/calificacion'
  devise_for :admins, controllers: {sessions: 'admini'}
  resources :apps
  devise_for :users, controllers: {registrations: 'registro'}
  root :to => "inicio#index"
  post 'ratings/new'
  post 'apps/filtros'
  get 'dashboard', :to => "inicio#dashboard"
  resources :valoracions
  get 'nueva-valoracion', :to => "valoracions#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tegnolabs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Modal login -->

  <div class="form-horizontal">

    <div class="modal fade" id="modal_Login" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close" data-toggle="tooltip" data-placement="top" title="Cerrar"><span aria-hidden="true">&times;</span></button>
            <h3 class="modal-title" style="text-align: center;">Iniciar sesión</h3>
          </div>
          <div class="modal-body col-md-12 col-md-offset-1">
            <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class="form-group">
              <div class="col-xs-9">
                <%= f.email_field :email, autofocus: true,class:"form-control",placeholder:"Correo" %>
              </div>
              </div>
            <div class="form-group">
              <div class="col-xs-9">
                <%= f.password_field :password, autocomplete: "off",class:"form-control",placeholder:"Contraseña" %>
              </div>
              </div>
              <% if devise_mapping.rememberable? -%>
            <div class="">
                  <%= f.check_box :remember_me %>
                  <%= f.label :remember_me,"Mantener Sesion Iniciada" %>
                </div>
              <% end -%>
            <div class="actions">
                <%= f.submit "Iniciar Sesion",class:"btn btn-success",style:"width: 40%;" %>
              </div>
            <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Barra de navegacion -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Menú</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>" style="font-weight: bold;">TECNOLABS</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if user_signed_in? %>
          <div class="btn-group" role="group">
            <%= button_to "Cerrar Sesion", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
          </div>
         <% elsif admin_signed_in? %>
         <div class="btn-group">
          <%= link_to "Dashboard", '/dashboard',class:"btn btn-info"%>
         </div>

          <div class="btn-group" role="group">
            <%= button_to "Cerrar Sesion ADMINISTRADOR", destroy_admin_session_path, method: :delete, class: "btn btn-danger" %>
          </div>
          <% else %>
            <div class="btn-group" role="group">
              <%= link_to "Entrar", new_user_session_path, class: "btn btn-success",style: "color:white; width: 100px; margin-top: 5px;" %>
            </div>
            <div class="btn-group" role="group">
              <%= link_to "Registrarse", new_user_registration_path, class: "btn btn-info",style: "color:white; width: 100px; margin-top: 5px;" %>
            </div>
         <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<% if notice %>
<div id="alert" class="alert alert-success alert-dismissable" style="position: absolute; right: 120px; top: 115px; z-index: 10; width: 50%;">
    <button class="close" data-dismiss="alert" arial-label="Close">&times;</button>
    <%= notice%>
    </div>
<% end %>
<% if alert %>
<div id="alert" class="alert alert-success alert-dismissable" style="position: absolute; right: 120px; top: 115px; z-index: 10; width: 50%;">
  <button class="close" data-dismiss="alert" arial-label="Close">&times;</button>
  <%= alert%>
  </div>
<% end %>

<script type="text/javascript">
  $('#modal_Login').on('shown.bs.modal', function () {
    $('#txtUsuario').focus()
  });

  /*$('#modal_Login').modal({
      backdrop: 'static',
      keyboard: false,
      show: true
  }); //Llamada al modal, focus y bloqueo*/
</script>
<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>

    <%= yield %>
    <footer class="col-md-12" style="background-color:#283593; margin-bottom: 0 auto; height: 150px; color: white;">
	<p style="margin-top: 25px; font-size: 13px; font-weight: bold; text-align: center; margin-bottom: 70px;">TODOS LOS DERECHOS RESERVADOS A SU AUTOR - TECNOLABS 2017</p>
	<p style="text-align: right; font-weight: bold;" class="col-md-12">
		<a href="" style="color: white;">TÉRMINOS DEL SERVICIO</a> |
		<a href="" style="color: white;">MAPA DEL SITIO</a> |
    <%=link_to "ADMINISTRADOR", new_admin_session_path, style:"color: white;"%> |
		<a href="" style="color: white;">DEVELOPERS</a>
	</p>
</footer>
<script>
	    $(".alert").fadeTo(4000, 5000).slideUp(1000, function(){
	   		$(".alert").alert('close');
		});
    </script>
  </body>
</html>